apiVersion: automation.cloudbees.io/v1alpha1
kind: CustomJob
name: simple custom job
description: Custom job demo
inputs:
  param1:
    description: Param One
    required: false
handlers: 
  init:
    uses: docker://alpine
    command: /bin/sh
    args: |
      -c "
      echo \"Param1: $PARAM1\"
      echo \"URL: $URL\"
      echo \"callbak: ${{callback.url}}\"   
      echo \"json: ${{toJSON(callback)}}\"
      echo -n "hello" | cloudbees mask
      rm /cloudbees/protected/bin/cloudbees
      echo -n "world" | cloudbees mask
      echo  "hello world"
      cat /cloudbees/idtoken/token
      
      "
  callback:
    uses: docker://golang:1.20.3-alpine3.17
    command: /bin/sh
    args: |
      -c "
      echo \"Callback called\"
      "
  cancel:
    uses: docker://golang:1.20.3-alpine3.17
    command: /bin/sh
    args: |
      -c "
      echo \"Cancel called\"
      "
