apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
      
jobs:
    custom:
        delegates: cb-nsrinivasa/custom-job/.cloudbees/workflows/custom.yaml
        with:
            param1: "asdf"
        timeout-minutes: 30
        
    build:
      needs: custom
      steps:
        - name: Say hello
          uses: docker://golang:1.20.3-alpine3.17
          shell: sh
          run: |
            echo "hello world ${{ needs.custom.outputs.result }}"
