apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
      
jobs:
    custom:
        delegates: cb-nsrinivasa/custom-job/.cloudbees/workflows/custom.yaml@v1
        with:
            some-arg: ${{ vars.testpropertymlcb404 }}
        secrets:
            asecret: ${{ secrets.testsecret1 }}
        timeout-minutes: 4311
